# Model
model_name: /mnt/publiccache/huggingface/Meta-Llama-3-8B
model_class: AutoModelForCausalLM
tokenizer_class: AutoTokenizer
tokenizer_name: /mnt/publiccache/huggingface/Meta-Llama-3-8B
model_parallel: false
inner_params:
- model.layers.29.mlp.gate_proj.weight
- model.layers.29.mlp.up_proj.weight
- model.layers.29.mlp.down_proj.weight
- model.layers.30.mlp.gate_proj.weight
- model.layers.30.mlp.up_proj.weight
- model.layers.30.mlp.down_proj.weight
- model.layers.31.mlp.gate_proj.weight
- model.layers.31.mlp.up_proj.weight
- model.layers.31.mlp.down_proj.weight

# The filepath of trained MEND.
archive: ./train_output/MEND_2024-10-27-10-18/models/Meta-Llama-3-8B.bk

# For Mulfe
mulfe:
  probe_field: generated_probes
  edit_field: doc
  n_aug_per_sample: 0
  n_outer_per_sample: 3
  n_loc_per_sample: 5
  seed: 42
  loss_type: nll
  memorizing: false

# Method
alg: MEND
lr: 1e-7
edit_lr: 1e-5
lr_lr: 1e-5
seed: 42
cedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null

mend:
  one_sided: False
  n_hidden: 1
  hidden_dim: null
  init: id
  norm: True
  combine: True
  x_only: False
  delta_only: False
  act: relu
  rank: 1920
  mlp_class: IDMLP
  shared: True

# Train
device: cuda:0
batch_size: 1
model_save_pt: 5000
silent: False
#max_epochs: 1
max_iters: 100000
log_interval: 1000
eval_log_interval: 1000
final_eval: True
val_interval: 1000
early_stop_patience: 30000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
debug: False
save: False
verbose: True

val_batch_size: 1
accumulate_bs: 10
val_steps: 500 # only for debug
opt: Adam
grad_clip: 100.

# Output

results_dir: ./train_output